# Generated by Django 5.1.4 on 2025-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('شگفت انگیز', 'شگفت انگیز'), ('عادی', 'عادی')], default='عادی', max_length=50, verbose_name='نوع محصول'),
        ),
    ]
