# Generated by Django 5.1.4 on 2025-01-23 12:11

import django.utils.timezone
import django_jalali.db.models
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(help_text='مثال: ۰۹۱۲۳۴۵۶۷۸۹', max_length=15, unique=True, validators=[user.models.validate_iranian_phone], verbose_name='شماره تلفن')),
                ('first_name', models.CharField(blank=True, max_length=25, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='نام خانوادگی')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود')),
                ('joined', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('profile_image', models.ImageField(blank=True, default='default_profile.png', upload_to='users/profiles/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
